src/main/java/com/unileon/controlador/BloquearUsuarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unileon.controlador;

import com.unileon.EJB.UsuarioFacadeLocal;
import com.unileon.modelo.Usuario;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jorgmateos
 */

// Para que pueda ser vista desde el html.
// Si ni ponemos nombre en @Named accederemos a ella de la misma forma pero empezando x minúscula.
@Named
@ViewScoped
public class BloquearUsuarioController implements Serializable {
    
    @EJB
    private UsuarioFacadeLocal usuarioEJB;
    
    // Lista de usuarios
    private List<Usuario> listaUsuarios;
    
    
    @PostConstruct
    public void inicio(){
    
        this.listaUsuarios = this.usuarioEJB.findAll();
        
    }
    
    // Getters & setters
    public UsuarioFacadeLocal getUsuarioEJB() {
        return usuarioEJB;
    }

    public void setUsuarioEJB(UsuarioFacadeLocal usuarioEJB) {
        this.usuarioEJB = usuarioEJB;
    }

    public List<Usuario> getListaUsuarios() {
        return listaUsuarios;
    }

    public void setListaUsuarios(List<Usuario> listaUsuarios) {
        this.listaUsuarios = listaUsuarios;
    }

    /**
     * Método para bloquear al usuario -> se cambia su estado
     * @param user
     */
    public void bloquearUser(Usuario user){
    
        try {
            
            // Cambiamos el estado del usuario
            user.setEstado(true);
            
            // Seteamos el contador a un número mayor que 5
            user.setContadorInicioSesion(6);
            
            // Cambiamos el estado del usuario en la BDD
            this.usuarioEJB.edit(user);
        
        
        } catch (Exception e) {
        
            System.out.println("Error al bloquear usuario: "+e.getMessage());
        
        }
    
    }
    
    /**
     * Método para desbloquear al usuario -> se cambia su estado
     * @param user
     */
    public void desbloquearUser(Usuario user){
    
        try {
            
            // Cambiamos el estado del usuario
            user.setEstado(false);
            
            // Seteamos el contador a 0
            user.setContadorInicioSesion(0);
            
            // Cambiamos el estado del usuario en la BDD
            this.usuarioEJB.edit(user);
        
        
        } catch (Exception e) {
        
            System.out.println("Error al desbloquear usuario: "+e.getMessage());
        
        }
    
    }
    
    
} 

src/main/java/com/unileon/controlador/CarritoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unileon.controlador;

import com.unileon.EJB.MisProductosFacadeLocal;
import com.unileon.EJB.UsuarioFacadeLocal;
import com.unileon.modelo.MisProductos;
import com.unileon.modelo.Producto;
import com.unileon.modelo.Usuario;
import com.unileon.utils.Utils;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author jorgmateos
 */
// Para que pueda ser vista desde el html.
// Si ni ponemos nombre en @Named accederemos a ella de la misma forma pero empezando x minúscula.
@Named
@SessionScoped
public class CarritoController implements Serializable{
    
    @EJB
    private UsuarioFacadeLocal usuarioEJB;
    
    @EJB
    private MisProductosFacadeLocal misProductosEJB;
    
    private List<Producto> listaProductos;
    private List<Integer> listaPrecios;
    private List<Character> listaTipos;
    
    private int numProductos;
    private int total;
    
    @PostConstruct
    public void inicio(){
            
        this.listaProductos = new ArrayList<>();
        this.listaPrecios = new ArrayList<>();
        this.listaTipos = new ArrayList<>();
        
        this.calcularNumProductos();
        
        this.calcularTotal();
        
    }
    
    // Getters & setters

    public UsuarioFacadeLocal getUsuarioEJB() {
        return usuarioEJB;
    }

    public void setUsuarioEJB(UsuarioFacadeLocal usuarioEJB) {
        this.usuarioEJB = usuarioEJB;
    }

    public MisProductosFacadeLocal getMisProductosEJB() {
        return misProductosEJB;
    }

    public void setMisProductosEJB(MisProductosFacadeLocal misProductosEJB) {
        this.misProductosEJB = misProductosEJB;
    }

    public List<Producto> getListaProductos() {
        return listaProductos;
    }

    public void setListaProductos(List<Producto> listaProductos) {
        this.listaProductos = listaProductos;
    }

    public int getTotal() {
        return total;
    }

    public void setTotal(int total) {
        this.total = total;
    }

    public List<Integer> getListaPrecios() {
        return listaPrecios;
    }

    public void setListaPrecios(List<Integer> listaPrecios) {
        this.listaPrecios = listaPrecios;
    }

    public int getNumProductos() {
        return numProductos;
    }

    public void setNumProductos(int numProductos) {
        this.numProductos = numProductos;
    }

    public List<Character> getListaTipos() {
        return listaTipos;
    }

    public void setListaTipos(List<Character> listaTipos) {
        this.listaTipos = listaTipos;
    }
    
    

    /**
     * Método que calcula el precio total de los productos
     */
    public void calcularTotal() {
        
        this.total = 0;

        if (this.listaPrecios.isEmpty())
            this.total = 0;
        else {
        
            for (int i = 0; i < this.listaPrecios.size(); i++)
                this.total += this.listaPrecios.get(i);
        }

    }

    /**
     * Método que calcula el número total de productos en el carrito
     */
    private void calcularNumProductos() {
        
        this.numProductos = this.listaProductos.size();
        
    }
    
    /**
     * Método que devuelve si se debe rednerizar o no el número de elementos
     * @return true si se puede renderizar, false si no
     */
    public boolean renderNumProductos(){
    
        // Se podrá renderizar el número de elementos en el carrito
        // cuando haya algún elemento en el carrito
            return this.numProductos != 0;
        
    }
    
    /**
     * Método para añadir una compra al carrito
     * @param producto 
     */
    public void anadirCompra(Producto producto){

        if (!this.isEnCarrito(producto)){
            
            // Añadimos el producto a la lista de productos
            this.listaProductos.add(producto);
            
            // Añadimos el precio a la lista de precios
            this.listaPrecios.add(producto.getPrecioCompra());
            
            // Añadimos el tipo de compra/alquiler
            this.listaTipos.add('C');
            
            // Calculamos el nuevo número de productos
            this.calcularNumProductos();
        
            // Calculamos el precio todoal
            this.calcularTotal();
            
        } else 
             System.out.println("Error al añadir compra al carrito");   
        
    }
    
    public void anadirAlquiler(Producto producto){
    
        if (!this.isEnCarrito(producto)){
            
            // Añadimos el producto a la lista de productos
            this.listaProductos.add(producto);
            
            // Añadimos el precio a la lista de precios
            this.listaPrecios.add(producto.getPrecioAlquiler());
            
            // Añadimos el tipo de compra/alquiler
            this.listaTipos.add('A');
            
            // Calculamos el nuevo número de productos
            this.calcularNumProductos();
        
            // Calculamos el precio todoal
            this.calcularTotal();
            
        } else 
             System.out.println("Error al añadir alquiler al carrito");   
    
    }


    /**
     * Método para comprobar si un producto está en el carrito o no
     * @param producto
     * @return 
     */
    public boolean isEnCarrito(Producto producto) {
        
        for (int i = 0; i < this.listaProductos.size(); i++){
                    
            if (producto.equals(this.listaProductos.get(i))){
                return true;
            }
            
        }
        
        return false;

    }
    
    /**
     * Método que devuelve el índice del producto dentro de la lista de productos
     * del carrito
     * @param producto 
     */
    private int getProductIndex(Producto producto){
    
        for (int i = 0; i < this.listaProductos.size(); i++){
        
            if (this.listaProductos.get(i).equals(producto))
                return i;
            
        }
        
        return -1;
        
    }
    
    /**
     * Método que comprueba si el producto que se ha añadido a la lista
     * de productos del carrito comprándolo
     * @param producto
     * @return 
     */
    public boolean isCompra(Producto producto){
    
        int indiceProducto = this.getProductIndex(producto);
        
        if (indiceProducto == -1)
            return false;
        else {
        
            return (this.listaTipos.get(indiceProducto) == 'C');
            
        }
        
    }
    
    /**
     * Método que comprueba si el producto que se ha añadido a la lista
     * de productos del carrito alquiándolo
     * @param producto
     * @return 
     */
    public boolean isAlquiler(Producto producto){
    
        int indiceProducto = this.getProductIndex(producto);
        
        if (indiceProducto == -1)
            return false;
        else {
        
            return (this.listaTipos.get(indiceProducto) == 'A');
            
        }
    
    }
    
    /**
     * Método que elimina el producto pasado como parámetro de la lista de
     * productos del carrito y la actualiza
     * @param producto 
     */
    public void deleteProducto(Producto producto){
        
        
        // Obtenemos el índice el producto
        int indice = this.getProductIndex(producto);
        
        if (indice != -1){
        
            // Eliminamos el producto de la lista de productos
            this.listaProductos.remove(indice);

            // Eliminamos el tipo de compra de la lista de tipos
            this.listaTipos.remove(indice);

            // Eliminamos el precio de la lista de precios
            this.listaPrecios.remove(indice);

            // Actualizamos los valores
            this.calcularNumProductos();

            this.calcularTotal();
            
        } else 
            System.out.println("Error eliminar producto");
        
    }
    
    /**
     * Método que devuelve el nombre de usuario del usuario de la sesión
     * @return 
     */
    public String getUsername(){
    
        return Utils.getCurrentUserSession().getUsername();
        
    }
    
    /**
     * Método que devuelve el saldo del usuario de la sesión
     * @return 
     */
    public int getSaldo(){
    
        return Utils.getCurrentUserSession().getSaldo();
        
    }
    
    /**
     * Método que decuelve boolean para que se pueda realizar el procesamiento de 
     * la compra/alquler o no
     * @return 
     */
    public boolean renderProcesar(){
    
        /**
         * Devuelve true (botón bloqueado) si:
         *  - el saldo del usuario es inferior al total
         * OR
         *  - el número de productos es 0 (no hay ningún producto)
         * */
        
        return ((this.saldoInsuficiente()) || (this.numProductos == 0));
    
    }
    
    /**
     * Método que devuelve un boolean indicando si el usuario dispone del saldo
     * suficiente para realizar la compra o no
     * @return 
     */
    public boolean saldoInsuficiente(){
    
        return (Utils.getCurrentUserSession().getSaldo() < this.total);
        
    }
    
    /**
     * Método para calcular el saldo restante tras la compra/alquiler
     * @return 
     */
    public int calcularRestante(){
    
        return (Utils.getCurrentUserSession().getSaldo() - total);
    
    }
    
    private boolean isCompra(char tipo){
    
        return tipo == 'C';
    
    }
    
    /**
     * Método que procesa la compra del usuario
     */
    public void procesarCompra() {
        
        try{
        
            for (int i = 0; i < this.listaProductos.size(); i++){

src/main/java/com/unileon/controlador/CrearNoticiasController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unileon.controlador;

import com.unileon.EJB.CatNoticiasFacade;
import com.unileon.EJB.CatNoticiasFacadeLocal;
import com.unileon.EJB.NoticiasFacadeLocal;
import com.unileon.EJB.ProductoFacadeLocal;
import com.unileon.EJB.TipoProductoFacadeLocal;
import com.unileon.modelo.CatNoticias;
import com.unileon.modelo.Noticias;
import com.unileon.modelo.Producto;
import com.unileon.modelo.TipoProducto;
import com.unileon.utils.Utils;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Usuario
 */
@Named
@ViewScoped
public class CrearNoticiasController implements Serializable {

    @EJB
    private NoticiasFacadeLocal noticiaEJB;

    @EJB
    private CatNoticiasFacadeLocal CatNoticiaEJB;

    
   @Inject
   private Noticias noticia;
   @Inject
   private CatNoticias CatNoticia;
   
     private List<Noticias> noticias;
     private List<CatNoticias> tipoNoticias;
     
     @PostConstruct
   public void inicio(){
   
        this.noticias = noticiaEJB.findAll();
        this.tipoNoticias = CatNoticiaEJB.findAll();
   
   }
   
   public void crearNoticias(){
       //Seteamos el tipo de producto

       this.noticia.setCategoriaId(CatNoticia);
       this.noticia.setUsuario(Utils.getCurrentUserSession());
       
       if(siExiste()){
             FacesContext.getCurrentInstance().addMessage("messages",
                    new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", "El producto ya existe"));
       }else{
           this.noticiaEJB.create(noticia);
           FacesContext.getCurrentInstance().addMessage("messages",
                        new FacesMessage(FacesMessage.SEVERITY_INFO, "Aviso", "Producto creado con éxito"));
       }
   }

    public NoticiasFacadeLocal getNoticiaEJB() {
        return noticiaEJB;
    }

    public void setNoticiaEJB(NoticiasFacadeLocal noticiaEJB) {
        this.noticiaEJB = noticiaEJB;
    }

    public CatNoticiasFacadeLocal getCatNoticiaEJB() {
        return CatNoticiaEJB;
    }

    public void setCatNoticiaEJB(CatNoticiasFacadeLocal CatNoticiaEJB) {
        this.CatNoticiaEJB = CatNoticiaEJB;
    }

    public Noticias getNoticia() {
        return noticia;
    }

    public void setNoticia(Noticias noticia) {
        this.noticia = noticia;
    }

    public CatNoticias getCatNoticia() {
        return CatNoticia;
    }

    public void setCatNoticia(CatNoticias CatNoticia) {
        this.CatNoticia = CatNoticia;
    }

    public List<Noticias> getNoticias() {
        return noticias;
    }

    public void setNoticias(List<Noticias> noticias) {
        this.noticias = noticias;
    }

    public List<CatNoticias> getTipoNoticias() {
        return tipoNoticias;
    }

    public void setTipoNoticias(List<CatNoticias> tipoNoticias) {
        this.tipoNoticias = tipoNoticias;
    }

    private boolean siExiste() {
         for(int i = 0; i < this.noticias.size();i++){
            if(noticia.equals(noticias.get(i)))
                return true;
        }
        
        
       return false;
    }
     
}

src/main/webapp/private/administrador/bloquearUsuario.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <head>
        <title>Crear usuario</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>

        <ui:composition template="./../../WEB-INF/template/plantillaPrincipal.xhtml">
            <ui:define name="content">

                <h:body>

                    <p:messages id="messages" showDetail="true" closable="true">
                        <p:autoUpdate />
                    </p:messages>

                    <h:form id="form">

                        <p:dataTable var="user" value="#{bloquearUsuarioController.listaUsuarios}" 
                                     style="margin-top: 10px; text-align: center">
                            <f:facet name="header">
                                LISTA DE USUARIOS
                            </f:facet>
                            <p:column headerText="ID" sortBy="#{user.idUsuario}">
                                <h:outputText value="#{user.idUsuario}" />
                            </p:column>

                            <p:column headerText="Username" sortBy="#{user.username}">
                                <h:outputText value="#{user.username}" />
                            </p:column>

                            <p:column headerText="Saldo" sortBy="#{user.saldo}">
                                <h:outputText value="#{user.saldo}" />
                            </p:column>

                            <p:column headerText="Estado">
                                <h:outputText rendered="#{user.estado}" value="BLOQUEADO"
                                              style="font-weight: bold; color: #990033"/>
                                <h:outputText rendered="#{not user.estado}" value="DESBLOQUEADO"
                                              style="font-weight: bold; color: #009966"/>                            
                            </p:column>
                            
                            <p:column headerText="Cambiar estado">
                                <p:commandLink rendered="#{not user.estado}" 
                                               action="#{bloquearUsuarioController.bloquearUser(user)}"
                                               update="form">
                                        <h:outputText styleClass="fa fa-fw fa-toggle-on" 
                                                      style="font-size: 20px; 
                                                        margin-top: 2px; 
                                                        color: #009966;"/>
                                </p:commandLink>
                                <p:commandLink rendered="#{user.estado}" 
                                               action="#{bloquearUsuarioController.desbloquearUser(user)}"
                                               update="form">
                                        <h:outputText styleClass="fa fa-fw fa-toggle-off" 
                                                      style="font-size: 20px; 
                                                        margin-top: 2px; 
                                                        color: #990033;"/>
                                </p:commandLink>
                            </p:column>
                            
                        </p:dataTable>

                    </h:form>       
                </h:body>
            </ui:define>
        </ui:composition>

    </body>

    <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces" />    
</html>

src/main/webapp/private/administrador/centroDeMensajes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head>
        <title>Buzón de entrada</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>

        <ui:composition template="./../../WEB-INF/template/plantillaPrincipal.xhtml">
            <ui:define name="content">

                <p:messages id="messages" showDetail="true" closable="true">
                    <p:autoUpdate />
                </p:messages>

                <h:form id="form">

                    <p:dataTable value="#{mensajesController.buzonEntradaUsuarios}" 
                                    var="mensaje">
                        
                        <p:column headerText="Emisor" style="width: 40px; text-align: center">
                            <p:outputLabel value="#{mensaje.emisor.username}" style="font-weight: bold;"/>
                        </p:column>
                        
                        <p:column headerText="Receptor" style="width: 40px; text-align: center">
                            <p:outputLabel value="#{mensaje.receptor.username}" style="font-weight: bold;"/>
                        </p:column>
                        
                        <p:column headerText="Asunto" style="width: 10%">
                            <p:outputLabel value="#{mensajesController.truncateText(mensaje.asunto, 25)}"/>
                        </p:column>
                        
                         <p:column headerText="Contenido" style="width: 28%">
                             <p:outputLabel value="#{mensajesController.truncateText(mensaje.contenido, 80)}" style="font-weight: lighter; color: #857369"/>
                        </p:column>
                        
                        <p:column headerText="Fecha" style="width: 5%; text-align: center">
                            <p:outputLabel value="#{mensajesController.fechaFormateada(mensaje.fecha)}"/>
                        </p:column>
                        
                         <p:column headerText="Ver" style="width: 2.5%; text-align: center">
                             <p:commandLink rendered="#{ not mensaje.estado}" style="color: red; font-size: 14px">
                                 <h:outputText styleClass="fa fa-fw fa-circle"/>
                             </p:commandLink>
                             <p:commandLink update=":form:verMensaje" oncomplete="PF('verMas').show()" title="Ver más">
                                 <p:tooltip showEffect="clip"/>
                                 <h:outputText styleClass="fa fa-fw fa-search" />
                                 <f:setPropertyActionListener value="#{mensaje}" target="#{mensajesController.mensaje}" />
                             </p:commandLink>
                        </p:column>
                        
                    </p:dataTable> 
                    
                    
                    <p:dialog header="Ver más..." widgetVar="verMas" 
                              modal="true" showEffect="fade" hideEffect="fade" resizable="false" width="60%">
                            <p:outputPanel id="verMensaje">
                                <p:panelGrid  columns="2" style="width: 100%" >
                                    <h:outputText value="De: " />
                                    <h:outputText value="#{mensajesController.mensaje.emisor.username}" style="font-weight: bold"/>
                                    
                                    <h:outputText value="Para: " />
                                    <h:outputText value="#{mensajesController.mensaje.receptor.username}" style="font-weight: bold"/>

                                    <h:outputText value="Asunto: " />
                                    <h:outputText value="#{mensajesController.mensaje.asunto}" />
                                                                        
                                    <h:outputText value="Contenido " />
                                    <p:inputTextarea  readonly="true" style="width: 100%" value="#{mensajesController.mensaje.contenido}" />
                                    
                                </p:panelGrid>
                                
                            </p:outputPanel>
                        <f:ajax event="close" render="@all"/>
                    </p:dialog>
           
                </h:form>
               
            </ui:define>
        </ui:composition>
    </body>
    <h:outputStylesheet library="webjars" name="font-awesome/5.12.0/css/all.min-jsf.css" />
    <h:outputStylesheet library="webjars" name="font-awesome/5.12.0/css/v4-shims.min-jsf.css" />
</html>

src/main/webapp/private/administrador/crearNoticias.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


    <ui:composition template="./../../WEB-INF/template/plantillaPrincipal.xhtml">
        <ui:define name="content">
            <p:messages id="messages" showDetail="true" closable="true">
                <p:autoUpdate />
            </p:messages>
            <h:form>


                <p:growl id="msg"/>
                <p:fieldset legend="Datos Noticias" style="margin-bottom:20px">
                    <p:panelGrid id="grid1" columns="3" layout="grid">

                        <p:outputLabel for="titulo" value="Nombre:"/>
                        <p:inputText id="titulo" required="true"
                                     requiredMessage="Nombre es un campo obligatorio"
                                     value="#{crearNoticiasController.noticia.nombre}"/>
                        <p:message for="titulo"/>

                        <p:outputLabel for="descripcion" value="Descripcion:"/>
                        <p:inputText id="descripcion" required="true"
                                     requiredMessage="Descripcion es un campo obligatorio"
                                     value="#{crearNoticiasController.noticia.descripcion}"/>
                        <p:message for="descripcion"/>

                        <p:outputLabel for="url" value="URL imagen:"/>
                        <p:inputText id="url" required="true"
                                     requiredMessage="url no es un campo obligatorio" 
                                     value="#{crearNoticiasController.noticia.url}"/>
                        <p:message for="url"/>

                        <p:outputLabel for="fecha" value="Fecha de publicación:"/>
                        <p:calendar id="fecha" required="true" locale="es"
                                    requiredMessage="Fecha de publicación es un campo obligatorio"
                                    value="#{crearNoticiasController.noticia.fechaPublicacion}"/>
                        <p:message for="fecha"/>

                        <p:outputLabel for="tipoProducto" value="Tipo Noticias: "/>
                        <p:selectOneMenu id="tipoProducto" value="#{crearNoticiasController.catNoticia.categoriaId}" >
                            <f:selectItems value="#{crearNoticiasController.tipoNoticias}" var="tipo"
                                           itemValue="#{tipo.categoriaId}" itemLabel="#{tipo.nombre}"/>
                        </p:selectOneMenu>
                        <p:message for="tipoProducto"/>




                    </p:panelGrid>
                </p:fieldset>
                <p:commandButton value="Registrar noticia" id="registrarButton" update="grid1"
                                 action="#{crearNoticiasController.crearNoticias()}"
                                 style= "margin-top:20px; 
                                 margin-left: 20px; 
                                 margin-bottom: 40px"
                                 />

            </h:form>

        </ui:define>
    </ui:composition>


</html>